---
- name: Configure workstations
  hosts: workstations
  roles:
    - 1password
    - role: gnome
      vars:
        set_interface_font: true
        set_document_font: true
        set_monospace_font: true
    - vscode
    - graphics_driver
    - rpmfusion
    - ffmpeg_swap
    - role: quiet_boot
      vars:
        quiet_boot: false
  vars_files:
    - vars/rpm_packages.yaml
    - vars/dnf_groups.yaml
    - vars/flatpak_packages.yaml

  tasks:

  - name: Update the system
    become: true
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Install individual rpm packages
    become: true
    ansible.builtin.dnf:
      name: "{{ rpm_packages }}"
      state: present

  - name: Install package groups
    become: true
    ansible.builtin.dnf:
      name: "@{{ item }}"
      state: present
    loop: "{{ dnf_groups }}"

  - name: Install flatpaks
    become: true
    ansible.builtin.flatpak:
      name: "{{ flatpak_packages }}"
      state: present
