---
gnome_mouse_acceleration_profile: "flat"
gnome_titlebar_button_layout: "appmenu:minimize,maximize,close"
# font changes via gsettings/dconf appear to
# break GNOME shell as of 50.x w F44.
gnome_set_interface_font: false
gnome_interface_font_name: "Adwaita Sans"
gnome_set_document_font: false
gnome_document_font_name: "Adwaita Sans"
gnome_set_monospace_font: false
gnome_monospace_font_name: "Adwaita Mono"
gnome_antialiasing_mode: "grayscale" # rgba none
