---
graphics_driver_nvidia_packages:
  - gcc # dep
  - kernel-headers # dep
  - kernel-devel # dep
  - akmod-nvidia
  - xorg-x11-drv-nvidia # driver
  - xorg-x11-drv-nvidia-libs # dep
  - xorg-x11-drv-nvidia-libs.i686 # dep
  - libva-nvidia-driver # media accel
graphics_driver_amd_packages: []
graphics_driver_intel_packages:
  - intel-media-driver
